[package]
name = "wasm-barnsley"
version = "0.2.0"
authors = ["Chris Snape-Jenkinson"]
edition = "2024"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]

[profile.release]
lto = true
# strip = true
strip = "debuginfo"
